### ISSUE TITLE
not working on ESP32 Arduino

### ISSUE THREAD

**Issue by ash73** [pololu/vl53l1x-st-api-arduino#5]
Hi, I've been using this library with a Arduino UNO with no problems but I can't get it working on a Wemos ESP32, it compiles ok in the Arduino IDE, and completes the setup steps but reports error -13 "error control interface" when it calls VL53L1_GetRangingMeasurementData in the loop. I think it may be a I2C problem.

I'm using the default pins 21 & 22, and I tried changing Wire.begin() to Wire.begin(SDA_PIN, SCL_PIN) as recommended elsewhere, but no luck.

Can you help?

**Comment by ash73** [comment]
@kazkojima has found a fix for this, ESP32 users need to apply a small mod to VL53L1_ReadMulti function in vl53l1_platform.cpp - see here:

https://github.com/kazkojima/esp32-vl53l1x-test/issues/2#issuecomment-410492702

**Comment by kevin-pololu** [comment]
I'm glad you found a solution. It sounds like the issue is coming from some unexpected/buggy behavior of `Wire.requestFrom()` on the ESP32 platform, and the workaround makes the code a little less efficient, so I'm inclined to leave vl53l1_platform.cpp alone for now unless we find out this affects other platforms too.

Thanks for linking to the other discussion, though; hopefully it will be useful to anyone else who runs into the same problem.
